import genuine from "./assets/Genuine.svg";
import quality from "./assets/quality.svg";
import safety from "./assets/safety.svg";
import shipping from "./assets/shipping.svg";
import support from "./assets/support.svg";
import wide from "./assets/wide.svg";
import shop from "./assets/shop.svg";
import delight from "./assets/delight.svg";
import call from "./assets/call.svg";
import priya from "./assets/priya.svg";
import rahul from "./assets/Rahul.svg";
import meera from "./assets/meera.svg";
import shot from "./assets/crackerImage.svg";

export const crackKingData = [
  {
    image: genuine, // Replace with the actual image path
    title: "Genuine Price",
    description:
      "Our main goal is to offer top-quality products at affordable prices.",
  },
  {
    image: quality, // Replace with another image path
    title: "Premium Quality",
    description:
      "Our firecrackers are carefully selected to ensure they are of the highest quality, delivering vibrant colors and thrilling effects.",
  },
  {
    image: safety, // Replace with the actual image path
    title: "Safety First",
    description:
      "We prioritize your safety by offering only products that meet strict safety standards. Each item is tested to ensure it’s safe and reliable.",
  },
  {
    image: shipping, // Replace with the actual image path
    title: "Fast Shipping",
    description:
      "Get your fireworks delivered right to your doorstep, just in time for your big event.",
  },
  {
    image: wide, // Replace with the actual image path
    title: "Wide Selection",
    description:
      "From sparklers to grand finales, we have the perfect firecrackers for every celebration.",
  },
  {
    image: support, // Replace with the actual image path
    title: "24/7 Customer Support",
    description:
      "Have questions? Our friendly team is here to assist you every step of the way.",
  },
  // Add more cards as needed
];

export const missionData = [
  {
    image: shop, // Replace with an actual image path or component
    title: "Shop Here!",
    description: "Discover a world of explosive fun. Add to cart now!",
  },
  {
    image: call, // Replace with an actual image path or component
    title: "Get in Touch",
    description: "Share your address for a hassle-free delivery.",
  },
  {
    image: delight, // Replace with an actual image path or component
    title: "Delivery Delight",
    description: "Your favorite crackers delivered right to your doorstep.",
  },
  // Add more card objects as needed
];

export const reviewData = [
  {
    // quote: "“",
    description:
      "I was hesitant to order crackers online but I'm so glad I did. The quality is top-notch and the variety is impressive. The website was easy to navigate & service was excellent.",
    image: priya, // Replace with the actual image path
    name: "Priya R",
  },
  {
    // quote: "“",
    description:
      "I was hesitant to order crackers online but I'm so glad I did. The quality is top-notch and the variety is impressive. The website was easy to navigate & service was excellent.",
    image: rahul, // Replace with the actual image path
    name: "Rahul K",
  },
  {
    // quote: "“",
    description:
      "Best Diwali ever! Thanks to Cracker’s King for the amazing crackers. The kids had a blast and the neighbors loved the show. Will definitely order again next year.",
    image: meera, // Replace with the actual image path
    name: "Meera",
  },
  {
    // quote: "“",
    description:
      "I was hesitant to order crackers online but I'm so glad I did. The quality is top-notch and the variety is impressive. The website was easy to navigate & service was excellent.",
    image: priya, // Replace with the actual image path
    name: "Priya R",
  },
  {
    // quote: "“",
    description:
      "I was hesitant to order crackers online but I'm so glad I did. The quality is top-notch and the variety is impressive. The website was easy to navigate & service was excellent.",
    image: rahul, // Replace with the actual image path
    name: "Rahul K",
  },
  {
    // quote: "“",
    description:
      "Best Diwali ever! Thanks to Cracker’s King for the amazing crackers. The kids had a blast and the neighbors loved the show. Will definitely order again next year.",
    image: meera, // Replace with the actual image path
    name: "Meera",
  },
  {
    // quote: "“",
    description:
      "Best Diwali ever! Thanks to Cracker’s King for the amazing crackers. The kids had a blast and the neighbors loved the show. Will definitely order again next year.",
    image: meera, // Replace with the actual image path
    name: "Meera",
  },
  // Add more review objects as needed
];

export const accordian = [
  {
    question: "Are your crackers safe for children?",
    desc: "Yes, all our crackers are designed with safety in mind and comply with safety standards. However, adult supervision is always recommended.",
  },
  {
    question: "Are your crackers safe for children?",
    desc: "Yes, all our crackers are designed with safety in mind and comply with safety standards. However, adult supervision is always recommended.",
  },
  {
    question: "Are your crackers safe for children?",
    desc: "Yes, all our crackers are designed with safety in mind and comply with safety standards. However, adult supervision is always recommended.",
  },
  {
    question: "Are your crackers safe for children?",
    desc: "Yes, all our crackers are designed with safety in mind and comply with safety standards. However, adult supervision is always recommended.",
  },
  {
    question: "Are your crackers safe for children?",
    desc: "Yes, all our crackers are designed with safety in mind and comply with safety standards. However, adult supervision is always recommended.",
  },
];

export const CRACKER_DATA = [
  {
    id: 1,
    title: "SPARKLERS",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/7-CM-Electric.png",
        title: "7 CM ELECTRIC SPARKLERS",
        cardPrice: "₹40.00",
        offerPrice: "₹8.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/7-CM-Colour.png",
        title: "7 CM COLOUR SPARKLERS",
        cardPrice: "₹45.00",
        offerPrice: "₹9.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "7 CM GREEN SPARKLERS",
        cardPrice: "₹55.00",
        offerPrice: "₹11.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "7 CM RED SPARKLERS",
        cardPrice: "₹65.00",
        offerPrice: "₹13.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/10-CM-Electric.png",
        title: "10 CM ELECTRIC SPARKLERS",
        cardPrice: "₹70.00",
        offerPrice: "₹14.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/10-CM-Colour.png",
        title: "10 CM COLOUR SPARKLERS",
        cardPrice: "₹80.00",
        offerPrice: "₹16.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 7,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/10-CM-Green.png",
        title: "10 CM GREEN SPARKLERS",
        cardPrice: "₹90.00",
        offerPrice: "₹18.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 8,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/10-Cm-Red.png",
        title: "10 CM RED SPARKLERS",
        cardPrice: "₹100.00",
        offerPrice: "₹20.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 9,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/12-CM-Electric.png",
        title: "12 CM ELECTRIC SPARKLERS",
        cardPrice: "₹100.00",
        offerPrice: "₹20.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 10,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/12-Cm-Colour.png",
        title: "12 CM COLOUR SPARKLERS",
        cardPrice: "₹110.00",
        offerPrice: "₹22.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 11,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/12-Cm-Green.png",
        title: "12 CM GREEN SPARKLERS",
        cardPrice: "₹130.00",
        offerPrice: "₹26.00",

        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 12,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/12-Cm-Red.png",
        title: "12 CM RED SPARKLERS",
        cardPrice: "₹142.50",
        offerPrice: "₹28.50",

        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 13,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/15-Cm-Electric.png",
        title: "15 CM ELECTRIC SPARKLERS",
        cardPrice: "₹150.00",
        offerPrice: "₹30.00",

        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 14,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/15-Cm-Colour.png",
        title: "15 CM COLOUR SPARKLERS",
        cardPrice: "₹180.00",
        offerPrice: "₹36.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 15,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "15 CM GREEN SPARKLERS",
        cardPrice: "₹200.00",
        offerPrice: "₹40.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 16,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "15 CM RED SPARKLERS",
        cardPrice: "₹225.00",
        offerPrice: "₹45.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 17,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/30-Cm-Electric.png",
        title: "30 CM ELECTRIC SPARKLERS",
        cardPrice: "₹150.00",
        offerPrice: "₹30.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 18,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/30-Cm-Colour.png",
        title: "30 CM COLOUR SPARKLERS",
        cardPrice: "₹180.00",
        offerPrice: "₹36.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 19,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/30-Cm-Green.png",
        title: "30 CM GREEN SPARKLERS",
        cardPrice: "₹200.00",
        offerPrice: "₹40.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 20,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/30-Cm-Red.png",
        title: "30 CM RED SPARKLERS",
        cardPrice: "₹225.00",
        offerPrice: "₹45.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 21,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/50-Cm-Electric.png",
        title: "50 CM ELECTRIC SPARKLERS",
        cardPrice: "₹677.50",
        offerPrice: "₹135.50",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 22,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/50-Colour.png",
        title: "50 CM COLOUR SPARKLERS",
        cardPrice: "₹800.00",
        offerPrice: "₹160.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
    ],
  },
  {
    id: 2,
    title: "Flower Pots",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/FP-Big.png",
        title: "FLOWER POTS BIG",
        cardPrice: "₹190.00",
        offerPrice: "₹38.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/FP-Small.png",
        title: "FLOWER POTS SMALL",
        cardPrice: "₹215.00",
        offerPrice: "₹43.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/FP-Special.png",
        title: "FLOWER POTS SPECIAL",
        cardPrice: "₹275.00",
        offerPrice: "₹55.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "FLOWER POTS GIANT/ASHOKA",
        cardPrice: "₹350.00",
        offerPrice: "₹70.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "FLOWER POTS DELUXE (1x5)",
        cardPrice: "₹600.00",
        offerPrice: "₹120.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/FP-Super-Deluxe.png",
        title: "FLOWER POTS (SUPER DLX) (1x2)",
        cardPrice: "₹480.00",
        offerPrice: "₹96.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 7,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Colour-Koti.png",
        title: "FLOWER POTS COLOUR KOTI",
        cardPrice: "₹750.00",
        offerPrice: "₹150.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special ",
      },
      {
        key: 8,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Tri-Colour.png",
        title: "TRI COLOUR FOUNTAIN (BRANDED)",
        cardPrice: "₹975.00",
        offerPrice: "₹195.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      //   {
      //     key: 9,
      //     image:"/crackerImage.svg",
      //     title: "TRI COLOUR FOUNTAIN (BRANDED)",
      //     cardPrice: "",
      //     offerPrice: "₹",
      //     size: "",
      //   },
    ],
  },
  {
    id: 3,
    title: "Ground Chakkers",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "GROUND CHAKKER BIG (10 Pcs)",
        cardPrice: "₹145.00",
        offerPrice: "₹29.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/GC-Asoka.png",
        title: "GROUND CHAKKER ASHOKA",
        cardPrice: "₹190.00",
        offerPrice: "₹38.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/GC-Special.png",
        title: "GROUND CHAKKER SPECIAL",
        cardPrice: "₹302.50",
        offerPrice: "₹68.50",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/GC-Deluxe.png",
        title: "GROUND CHAKKER DELUXE",
        cardPrice: "₹488.00",
        offerPrice: "₹98.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/GC-Super-Deluxe.png",
        title: "GROUND CHAKKER (SUPER DLX)",
        cardPrice: "₹1050.00",
        offerPrice: "₹210.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "G.CHAKKER DANCING WHEEL (5 Pcs)",
        cardPrice: "₹298.00",
        offerPrice: "₹60.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
    ],
  },
  {
    id: 4,
    title: "Novelties",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/7-Pencil.png",
        title: '7" PENCIL',
        cardPrice: "₹90.00",
        offerPrice: "₹18.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/12-Pencil.png",
        title: "12inch DELUXE PENCIL",
        cardPrice: "₹190.00",
        offerPrice: "₹38.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/16-Super-Deluxe-Pencil.png",
        title: '16" SUPER DLX PENCIL',
        cardPrice: "₹315.00",
        offerPrice: "₹63.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "3 COLOUR PENCIL",
        cardPrice: "₹360.00",
        offerPrice: "₹72.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Best Sellers",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "FLASH LIGHT TORCH",
        cardPrice: "₹270.00",
        offerPrice: "₹54.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Star-Rain.png",
        title: "STAR RAIN (CRACKLING)",
        cardPrice: "₹650.00",
        offerPrice: "₹130.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Fancy Items",
      },
      {
        key: 7,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Colour-Smoke.png",
        title: "COLOURS SMOKERS (3PCS)",
        cardPrice: "₹650.00",
        offerPrice: "₹130.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 8,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "HERO GUN (5 PCS)",
        cardPrice: "₹650.00",
        offerPrice: "₹130.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 9,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "ELECTRIC STONE BIG",
        cardPrice: "₹100.00",
        offerPrice: "₹20.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 10,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/1.5-Twinkling-Star.png",
        title: "1 1/2 TWINKLING STAR",
        cardPrice: "₹80.00",
        offerPrice: "₹16.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 11,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/4-Twinkling-Stsr.png",
        title: '4" TWINKLING STAR',
        cardPrice: "₹235.00",
        offerPrice: "₹47.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
    ],
  },
  {
    id: 5,
    title: "Single Sound",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/2-3.4-Kuruvi-Deluxe.png",
        title: "2 3/4 KURUVI DELUXE",
        cardPrice: "₹30.00",
        offerPrice: "₹6.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/3-1.5-Lakshmi_01.png",
        title: "3 1/2 LAKSHMI",
        cardPrice: "₹40.00",
        offerPrice: "₹8.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "4 LAKSHMI JOKER",
        cardPrice: "₹60.00",
        offerPrice: "₹12.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/4-Lakshmi-Deluxe_02.png",
        title: "4 DELUXE LAKSHMI",
        cardPrice: "₹100.00",
        offerPrice: "₹20.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Best Sellers",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/4-Gold-Lakshmi_01.png",
        title: "4 SUPER DELUXE/GOLD LAKSHMI",
        cardPrice: "₹132.50",
        offerPrice: "₹26.50",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Best Sellers",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/2+Sound+Crackers.png",
        title: "TWO SOUND CRACKERS",
        cardPrice: "₹125.00",
        offerPrice: "₹25.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 7,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Red-Bijili.png",
        title: "RED BIJILI (1X100)",
        cardPrice: "₹110.00",
        offerPrice: "₹22.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 8,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Stripped-Bijili.png",
        title: "STRIPPED BIJILI (1X100)",
        cardPrice: "₹125.00",
        offerPrice: "₹25.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 9,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "GOLD BIJILI (1X100)",
        cardPrice: "₹160.00",
        offerPrice: "₹32.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 10,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "RED BIJILI (1X50)",
        cardPrice: "₹55.00",
        offerPrice: "₹11.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 11,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "STRIPPED BIJILI (1X50)",
        cardPrice: "₹75.00",
        offerPrice: "₹15.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 12,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "GOLD BIJILI (1X50)",
        cardPrice: "₹90.00",
        offerPrice: "₹18.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
    ],
  },
  {
    id: 6,
    title: "Bombs",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Bullet-Bomb.png",
        title: "Bullet Bomb",
        cardPrice: "₹102.50",
        offerPrice: "₹20.50",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,

        type: "",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Atom-Bomb.png",
        title: "Atom Bomb Green",
        cardPrice: "₹200.00",
        offerPrice: "₹40.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Hydro-Bomb.png",
        title: "Hydro Bomb Green",
        cardPrice: "₹225.00",
        offerPrice: "₹45.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Winner-Bomb.png",
        title: "Classic/Winner K Bomb Green",
        cardPrice: "₹270.00",
        offerPrice: "₹54.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Vibrate-Bomb.png",
        title: "Vibrate/Corilla Classic",
        cardPrice: "₹335.00",
        offerPrice: "₹67.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,

        type: "",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Killer-Bomb.png",
        title: "Killer Delex (7 PLY)",
        cardPrice: "₹750.00",
        offerPrice: "₹150.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,

        type: "",
      },
      {
        key: 7,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Flower-Bomb.png",
        title: "Flower Bomb (1X5)",
        cardPrice: "₹300.00",
        offerPrice: "₹60.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,

        type: "",
      },
    ],
  },
  {
    id: 7,
    title: "Rockets",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Baby-Rocket.png",
        title: "Baby Rocket",
        cardPrice: "₹135.00",
        offerPrice: "₹27.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Rocket-Bomb.png",
        title: "Rocket Bomb/Colour Rocket",
        cardPrice: "₹210.00",
        offerPrice: "₹42.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Lunik-Rocket.png",
        title: "Lunik Rocket",
        cardPrice: "₹325.00",
        offerPrice: "₹65.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,

        type: "Kids special",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Two Sound Rocket",
        cardPrice: "₹357.50",
        offerPrice: "₹71.50",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,

        type: "Kids special",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Whistling-Rocket.png",
        title: "Whistling Rocket",
        cardPrice: "₹525.00",
        offerPrice: "₹105.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,

        type: "Kids special",
      },
    ],
  },
  {
    id: 8,

    title: "Peacocks",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Magic-Peacock-3--in-1.png",
        title: "Magic Peacock (3 in 1)",
        cardPrice: "₹675.00",
        offerPrice: "₹135.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Dancing-Peacock-5--in-1.png",
        title: "Dancing Peacock (5 in 1)",
        cardPrice: "₹750.00",
        offerPrice: "₹150.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,

        type: "",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Bada Peacock (5 in 1)",
        cardPrice: "₹1500.00",
        offerPrice: "₹300.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,

        type: "",
      },
    ],
  },
  {
    id: 9,
    title: "Colour Fancy",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Nayagara-Falls-Pencil.png",
        title: "Nayagara Falls Pencil",
        cardPrice: "₹400.00",
        offerPrice: "₹80.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Fancy Items",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Popcorn Pencil",
        cardPrice: "₹600.00",
        offerPrice: "₹120.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Photo-Flash.png",
        title: "Photo Flash",
        cardPrice: "₹312.50",
        offerPrice: "₹62.50",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Tin-Fountain.png",
        title: "Tin Fountain (6 Varieties)",
        cardPrice: "₹600.00",
        offerPrice: "₹120.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "New arrivals",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Old Is Gold",
        cardPrice: "₹750.00",
        offerPrice: "₹150.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Helicopter_02.png",
        title: "Helicopter",
        cardPrice: "₹450.00",
        offerPrice: "₹90.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "New arrivals",
      },
    ],
  },
  {
    id: 10,
    title: "Paper Bombs",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Paper-Bomb-Big.png",
        title: "Paper Bomb Big",
        cardPrice: "₹225.00",
        offerPrice: "₹45.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Paper-Bomb-Special.png",
        title: "Paper Bomb Special",
        cardPrice: "₹450.00",
        offerPrice: "₹90.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Paper-Bomb-Mega.png",
        title: "Paper Bomb Mega",
        cardPrice: "₹900.00",
        offerPrice: "₹180.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Vikram-Mega.png",
        title: "Vikram (Mega 10)",
        cardPrice: "₹1000.00",
        offerPrice: "₹200.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
    ],
  },
  {
    id: 11,
    title: "Fancy Items",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Bambara-Spinner.png",
        title: "Bambara Spinner",
        cardPrice: "₹525.00",
        offerPrice: "₹105.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Fancy Items",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Dancing-Butterfly.png",
        title: "Dancing Butterfly",
        cardPrice: "₹400.00",
        offerPrice: "₹80.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/7-Shot-5PCS.png",
        title: "7 Shot (5 Pcs)",
        cardPrice: "₹500.00",
        offerPrice: "₹100.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Colour-Siren.png",
        title: "Colour Siren",
        cardPrice: "₹800.00",
        offerPrice: "₹160.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Fancy Items",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "12 Star Rider",
        cardPrice: "₹600.00",
        offerPrice: "₹120.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "12 Star Red & Green",
        cardPrice: "₹500.00",
        offerPrice: "₹100.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 7,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Disco Shower",
        cardPrice: "₹525.00",
        offerPrice: "₹105.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Fancy Items",
      },
      {
        key: 8,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Twix / Super Heros",
        cardPrice: "₹550.00",
        offerPrice: "₹110.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Fancy Items",
      },
      {
        key: 9,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Fox-Star.png",
        title: "Fox Star / Brite",
        cardPrice: "₹700.00",
        offerPrice: "₹140.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Fancy Items",
      },
      {
        key: 10,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Sing-Pop_B.png",
        title: "Sing Pop",
        cardPrice: "₹750.00",
        offerPrice: "₹150.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "New arrivals",
      },
      {
        key: 11,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "H2O",
        cardPrice: "₹650.00",
        offerPrice: "₹130.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "New arrivals",
      },
      {
        key: 12,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Colour-Rain.png",
        title: "Colour Rain",
        cardPrice: "₹375.00",
        offerPrice: "₹75.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Fancy Items",
      },
      {
        key: 13,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Peacock-Feathers.png",
        title: "Peacock Feathers",
        cardPrice: "₹382.00",
        offerPrice: "₹76.50",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 14,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Golden-Globe.png",
        title: "Golden Globe",
        cardPrice: "₹375.00",
        offerPrice: "₹75.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Fancy Items",
      },
      {
        key: 15,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Lotus / 4x4 Wheel",
        cardPrice: "₹210.00",
        offerPrice: "₹42.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Best Sellers",
      },
    ],
  },
  {
    id: 12,
    title: "Night Boomers",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Penta-Colour-Flash.png",
        title: "Penta Colour Flash (5 Varieties/1 Box)",
        cardPrice: "₹660.00",
        offerPrice: "₹132.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Chotta-Fancyc.png",
        title: '1 1/2" Chotta Fancy (6 Varieties)',
        cardPrice: "₹210.00",
        offerPrice: "₹42.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: '3" Pieces Fancy Pipe (4 Varieties)',
        cardPrice: "₹1105.00",
        offerPrice: "₹221.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Best Sellers",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: '2" Fancy Pipe (6 Varieties)',
        cardPrice: "₹525.00",
        offerPrice: "₹105.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/3-PCS-Fancy-Pipe.png",
        title: '3" Fancy Pipe (6 Varieties)',
        cardPrice: "₹1050.00",
        offerPrice: "₹210.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Best Sellers",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: '3.5" Fancy Colour (6 Varieties)',
        cardPrice: "₹1250.00",
        offerPrice: "₹250.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 7,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: '4" Fancy Colour',
        cardPrice: "₹1500.00",
        offerPrice: "₹300.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 8,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: '6" Fancy Multi Colour (Mothers)',
        cardPrice: "₹2875.00",
        offerPrice: "₹575.00",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
    ],
  },
  {
    id: 13,
    title: "Multi Color Shots",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "12 Shot Multi Colour",
        offerPrice: "₹225",
        cardPrice: "₹1125",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/30-Shots.png",
        title: "30 Multi Colour Shots",
        offerPrice: "₹325",
        cardPrice: "₹1625",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "30 Multi Colour Shots (UV)",
        offerPrice: "₹350",
        cardPrice: "₹1750",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "50 Shot Colour Bomb",
        offerPrice: "₹700",
        cardPrice: "₹3500",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "60 Multi Colour Shots",
        offerPrice: "₹1400",
        cardPrice: "₹7000",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Best Sellers",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/120-Shots.png",
        title: "120 Multi Colour Shots",
        offerPrice: "₹2800",
        cardPrice: "₹14000",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Best Sellers",
      },
      {
        key: 7,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "240 Multi Colour Shots",
        offerPrice: "₹5600",
        cardPrice: "₹28000",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
    ],
  },
  {
    id: 14,
    title: "2K/24 Series",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Silver-Drop.png",
        title: "Silver Drop",
        offerPrice: "₹110",
        cardPrice: "₹550",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Beast-Show.png",
        title: "Beast Show",
        offerPrice: "₹140",
        cardPrice: "₹700",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "New arrivals",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/Toy-Toy.png",
        title: "Toy Toy",
        offerPrice: "₹120",
        cardPrice: "₹600",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "Kids special",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Wonder Three",
        offerPrice: "₹170",
        cardPrice: "₹850",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Jumbo Cracking",
        offerPrice: "₹180",
        cardPrice: "₹900",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Top Gun",
        offerPrice: "₹190",
        cardPrice: "₹950",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 7,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Pistal 5G",
        offerPrice: "₹190",
        cardPrice: "₹950",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "New arrivals",
      },
      {
        key: 8,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "10x10-Display",
        offerPrice: "₹2750",
        cardPrice: "₹13750",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 9,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Drone",
        offerPrice: "₹130",
        cardPrice: "₹650",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "New arrivals",
      },
      {
        key: 10,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Motu Batlu",
        offerPrice: "₹200",
        cardPrice: "₹1000",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "New arrivals",
      },
    ],
  },
  {
    id: 15,
    title: "Gift Boxes",
    sparklersData: [
      {
        key: 1,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Dora (19 Items)",
        offerPrice: "₹250",
        cardPrice: "₹250",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 2,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Moana (21 Items)",
        offerPrice: "₹280",
        cardPrice: "₹280",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 3,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Avengers (26 Items)",
        offerPrice: "₹310",
        cardPrice: "₹310",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 4,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Avatar (30 Items)",
        offerPrice: "₹400",
        cardPrice: "₹400",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 5,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Hulk (36 Items)",
        offerPrice: "₹460",
        cardPrice: "₹460",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 6,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Angry Bird (40 Items)",
        offerPrice: "₹550",
        cardPrice: "₹550",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 7,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Paradise (45 Items)",
        offerPrice: "₹620",
        cardPrice: "₹620",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 8,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Wonderful (50 Items)",
        offerPrice: "₹800",
        cardPrice: "₹800",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 9,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "Carnivel (55 Items)",
        offerPrice: "₹900",
        cardPrice: "₹900",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
      {
        key: 10,
        image:
          "https://crackerskingsassets.s3.ap-south-1.amazonaws.com/CrackersKingLogo_product.png",
        title: "VIP (60 Items)",
        offerPrice: "₹1000",
        cardPrice: "₹1000",
        size: "1 Box",
        quantity: 1,
        Selection: false,
        count: 0,
        imagePic: shot,
        type: "",
      },
    ],
  },
];
